// AssemblyBuilder.cs  (Editor only)
// Menu "GoF2/Build/Assembled Prefabs": the game keeps every visual object as several meshes (hull, lights,
// emissive, engines, LODs...) and assembles them in code at spawn time (Globals::getShipGroup,
// PlayerStation::PlayerStation, Level::createStaticObject / createAsteroids, PlayerTurret, Level::createScene
// for hangars and bars, StarMap...). Resources/GoF2Data/assemblies.json holds those composition rules
// (generated by Reference/tools/asset_conversion/assemblies/build_assemblies.py); this builds one prefab per
// assembled object in Resources/Assembled/<pack>/<category>/ (loaded at runtime with AssembledObject.Load), nesting the per-mesh prefabs made by
// "Build Materials And Prefabs".

using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using GoF2Remake.Visuals;

namespace GoF2Remake.EditorTools
{
    // ---- assemblies.json model (JsonUtility-compatible; empty arrays mean "not set") -----------------
    [System.Serializable] public class AsmPart
    {
        public string key, parent;    // hierarchy inside the assembly; parent "" = the prefab root
        public int mesh;              // resource id; 0 = empty transform (e.g. turret pivot)
        public string model;          // FBX path relative to Assets
        public int material;          // override material id (0 = the per-mesh prefab's material)
        public string role, variant, condition;
        public float[] position;      // game units, engine space, relative to parent
        public float[] rotation;      // euler degrees, engine space
        public float[] scale;
        public int[] lods;            // LOD levels this part is shown at; empty = not LOD-managed
    }
    [System.Serializable] public class AsmEntry
    {
        public string name, pack, category, origin, notes;
        public int root;
        public AsmPart[] parts;
        public float[] lodDistances;  // game units: switch from level i to i+1
        public float lastVisibleDistance;
        public float[] scale;
        public float[] spawnRotation;
        public string explosionModel;
    }
    [System.Serializable] public class AsmTable { public AsmEntry[] entries; }

    public static class AssemblyBuilder
    {
        /// <summary>FOV used to turn the original's LOD distances into LODGroup screen heights.</summary>
        const float ReferenceFov = 60f;
        const string OutRoot = ImportSettings.Root + "/Resources/" + AssembledObject.ResourcesFolder;

        static string R(string rel) => ImportSettings.Root + "/" + rel;

        [MenuItem("GoF2/Build/Assembled Prefabs", priority = 241)]
        public static void BuildAll()
        {
            var json = AssetDatabase.LoadAssetAtPath<TextAsset>(R("Resources/GoF2Data/assemblies.json"));
            if (json == null) { Debug.LogError("GoF2: assemblies.json not found"); return; }
            var table = JsonUtility.FromJson<AsmTable>(json.text);

            int made = 0, n = 0;
            var problems = new List<string>();
            try
            {
                foreach (var e in table.entries)
                {
                    if (n++ % 5 == 0 && EditorUtility.DisplayCancelableProgressBar("GoF2", "Assembling " + e.name, (float)n / table.entries.Length)) break;
                    if (Build(e, problems)) made++;
                }
            }
            finally { EditorUtility.ClearProgressBar(); }
            AssetDatabase.SaveAssets();
            Debug.Log($"GoF2: {made}/{table.entries.Length} assembled prefabs built in {OutRoot}."
                      + (problems.Count > 0 ? $" {problems.Count} problem(s):\n" + string.Join("\n", problems) : ""));
        }

        static bool Build(AsmEntry e, List<string> problems)
        {
            var root = new GameObject(e.name);
            try
            {
                var asm = root.AddComponent<AssembledObject>();
                asm.rootMeshId = e.root;
                asm.origin = e.origin;
                asm.lodDistancesGameUnits = e.lodDistances;
                asm.lastVisibleDistanceGameUnits = e.lastVisibleDistance;
                if (e.spawnRotation != null && e.spawnRotation.Length == 3)
                    asm.spawnRotationEngine = new Vector3(e.spawnRotation[0], e.spawnRotation[1], e.spawnRotation[2]);
                if (!string.IsNullOrEmpty(e.explosionModel))
                    asm.explosionPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(PrefabPath(e.explosionModel));

                // Create all parts first, then parent them (parents may be listed after their children).
                var nodes = new Dictionary<string, GameObject>();
                var created = new List<(AsmPart part, GameObject go)>();
                foreach (var p in e.parts)
                {
                    var go = p.mesh == 0 ? new GameObject(p.role) : InstantiatePart(p);
                    if (go == null) { problems.Add($"{e.name}: {p.model} not found"); continue; }
                    nodes[p.key] = go;
                    created.Add((p, go));
                }
                if (created.Count == 0) { problems.Add($"{e.name}: nothing to build"); return false; }

                var byLevel = new Dictionary<int, List<Renderer>>();
                var player = new List<GameObject>();
                var npc = new List<GameObject>();
                var conditional = new List<GameObject>();
                var conditions = new List<string>();
                foreach (var (p, go) in created)
                {
                    var parent = !string.IsNullOrEmpty(p.parent) && nodes.TryGetValue(p.parent, out var pg) ? pg.transform : root.transform;
                    go.transform.SetParent(parent, false);
                    go.transform.localPosition = GameToUnityPosition(p.position);
                    go.transform.localRotation = GameToUnityRotation(p.rotation);
                    if (p.scale != null && p.scale.Length == 3) go.transform.localScale = new Vector3(p.scale[0], p.scale[1], p.scale[2]);

                    if (p.variant == "player") player.Add(go);
                    else if (p.variant == "npc") { npc.Add(go); go.SetActive(false); }
                    if (!string.IsNullOrEmpty(p.condition))
                    {
                        conditional.Add(go);
                        conditions.Add(p.condition);
                        // Random parts (freighter containers) stay visible; state-dependent ones start hidden.
                        if (!p.condition.StartsWith("random")) go.SetActive(false);
                    }
                    if (p.lods != null)
                        foreach (int l in p.lods)
                        {
                            if (!byLevel.TryGetValue(l, out var list)) byLevel[l] = list = new List<Renderer>();
                            // Only the part's own renderers: nested parts register their own levels.
                            list.AddRange(go.GetComponents<Renderer>().Concat(OwnChildRenderers(go, nodes.Values)));
                        }
                }
                asm.playerVariantParts = player.ToArray();
                asm.npcVariantParts = npc.ToArray();
                asm.conditionalParts = conditional.ToArray();
                asm.conditions = conditions.ToArray();
                if (e.scale != null && e.scale.Length == 3) root.transform.localScale = new Vector3(e.scale[0], e.scale[1], e.scale[2]);

                if (e.lodDistances != null && e.lodDistances.Length > 0 && byLevel.Count > 0)
                    SetupLods(root, e, byLevel);

                string pack = string.IsNullOrEmpty(e.pack) ? "main" : e.pack;
                string outPath = $"{OutRoot}/{pack}/{e.category}/{e.name}.prefab";
                Directory.CreateDirectory(Path.GetDirectoryName(outPath));
                PrefabUtility.SaveAsPrefabAsset(root, outPath);
                return true;
            }
            finally { Object.DestroyImmediate(root); }
        }

        /// <summary>Renderers inside a part's own hierarchy, excluding other assembly parts parented under it.</summary>
        static IEnumerable<Renderer> OwnChildRenderers(GameObject part, IEnumerable<GameObject> allParts)
        {
            var others = new HashSet<Transform>(allParts.Where(g => g != part).Select(g => g.transform));
            foreach (var r in part.GetComponentsInChildren<Renderer>(true))
            {
                if (r.gameObject == part) continue;
                bool foreign = false;
                for (var t = r.transform; t != null && t != part.transform; t = t.parent)
                    if (others.Contains(t)) { foreign = true; break; }
                if (!foreign) yield return r;
            }
        }

        static GameObject InstantiatePart(AsmPart p)
        {
            GameObject go;
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(PrefabPath(p.model));
            if (prefab != null) go = (GameObject)PrefabUtility.InstantiatePrefab(prefab);
            else
            {
                // Mesh without a per-mesh prefab: use the FBX directly.
                var fbx = AssetDatabase.LoadAssetAtPath<GameObject>(R(p.model));
                if (fbx == null) return null;
                go = (GameObject)PrefabUtility.InstantiatePrefab(fbx);
            }
            var mat = FindMaterial(p.material);
            if (mat != null)
                foreach (var r in go.GetComponentsInChildren<Renderer>(true))
                    r.sharedMaterials = Enumerable.Repeat(mat, Mathf.Max(1, r.sharedMaterials.Length)).ToArray();
            return go;
        }

        static Material FindMaterial(int id)
        {
            if (id <= 0) return null;
            var guid = AssetDatabase.FindAssets($"mat_{id}_ t:Material", new[] { R("Materials") }).FirstOrDefault();
            return guid == null ? null : AssetDatabase.LoadAssetAtPath<Material>(AssetDatabase.GUIDToAssetPath(guid));
        }

        static string PrefabPath(string model) => R("Prefabs/" + Path.ChangeExtension(model.Substring("Models/".Length), ".prefab"));

        // Game -> Unity: (x, y, z) -> (x, y, -z) * metersPerUnit (see CLAUDE.md "Coordinates and scale").
        static Vector3 GameToUnityPosition(float[] p) =>
            p == null || p.Length != 3 ? Vector3.zero : new Vector3(p[0], p[1], -p[2]) * ImportSettings.ModelScale;

        // Mirroring Z flips the handedness: rotations about X and Y change sign, Z stays.
        static Quaternion GameToUnityRotation(float[] r) =>
            r == null || r.Length != 3 ? Quaternion.identity : Quaternion.Euler(-r[0], -r[1], r[2]);

        /// <summary>
        /// The original switches LOD meshes at camera distances (AEGeometry::setLodMeshes). A LODGroup works in
        /// screen height, so convert each distance for ReferenceFov: height = size / (2 * d * tan(fov/2)).
        /// </summary>
        static void SetupLods(GameObject root, AsmEntry e, Dictionary<int, List<Renderer>> byLevel)
        {
            var group = root.AddComponent<LODGroup>();
            int levels = e.lodDistances.Length + 1;
            var lods = new LOD[levels];
            // Placeholder heights (must be strictly decreasing) until the bounds are known.
            for (int l = 0; l < levels; l++)
                lods[l] = new LOD(1f - (l + 1f) / (levels + 1f),
                                  byLevel.TryGetValue(l, out var list) ? list.Distinct().ToArray() : new Renderer[0]);
            group.SetLODs(lods);
            group.RecalculateBounds();

            float tanHalf = Mathf.Tan(ReferenceFov * 0.5f * Mathf.Deg2Rad);
            float worldSize = group.size * root.transform.lossyScale.x;
            float Height(float gameUnits) => Mathf.Clamp01(worldSize / (2f * gameUnits * ImportSettings.ModelScale * tanHalf));
            float prev = 1f;
            for (int l = 0; l < levels; l++)
            {
                float d = l < e.lodDistances.Length ? e.lodDistances[l] : e.lastVisibleDistance;
                float h = d > 0f ? Height(d) : 0f;
                h = Mathf.Min(h, prev * 0.999f); // LODGroup needs strictly decreasing heights
                lods[l].screenRelativeTransitionHeight = h;
                prev = h;
            }
            group.SetLODs(lods);
        }
    }
}
